//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubRegistration
    {
        public int RegistrationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ClubID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string PreferredRole { get; set; }
        public string RoleJustification { get; set; }
        public string ProfileImagePath { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public string AssignedRole { get; set; }
        public Nullable<System.DateTime> RegisteredAt { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
    
        public virtual ApprovalStatusTable ApprovalStatusTable { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable1 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable2 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable3 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable4 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable5 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable6 { get; set; }
        public virtual CLUB CLUB { get; set; }
        public virtual CLUB CLUB1 { get; set; }
        public virtual CLUB CLUB2 { get; set; }
        public virtual CLUB CLUB3 { get; set; }
        public virtual CLUB CLUB4 { get; set; }
        public virtual CLUB CLUB5 { get; set; }
        public virtual CLUB CLUB6 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USER USER2 { get; set; }
        public virtual USER USER3 { get; set; }
        public virtual USER USER4 { get; set; }
        public virtual USER USER5 { get; set; }
        public virtual USER USER6 { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual SUBDEPARTMENT SUBDEPARTMENT { get; set; }
        public virtual UNIVERSITY UNIVERSITY { get; set; }
    }
}
