//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLUB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLUB()
        {
            this.ClubRegistrations = new HashSet<ClubRegistration>();
            this.EVENTS = new HashSet<EVENT>();
            this.Logins = new HashSet<Login>();
        }
    
        public int ClubID { get; set; }
        public string ClubName { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public int TotalClubCommitteeSeats { get; set; }
        public int AvailableClubCommitteeSeats { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int DepartmentID { get; set; }
        public int MentorID { get; set; }
        public string LogoImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int ApprovalStatusID { get; set; }
        public Nullable<int> SubDepartmentID { get; set; }
    
        public virtual ApprovalStatusTable ApprovalStatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubRegistration> ClubRegistrations { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENTS { get; set; }
        public virtual SUBDEPARTMENT SUBDEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
    }
}
