//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTMENT()
        {
            this.ClubRegistrations = new HashSet<ClubRegistration>();
            this.CLUBS = new HashSet<CLUB>();
            this.Logins = new HashSet<Login>();
            this.USERs = new HashSet<USER>();
            this.SUBDEPARTMENTs = new HashSet<SUBDEPARTMENT>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string HOD { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> Universityid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
        public string HOD_Email { get; set; }
        public string DirectorName { get; set; }
        public string DirectorEmail { get; set; }
        public Nullable<bool> IsDirectorDepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubRegistration> ClubRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLUB> CLUBS { get; set; }
        public virtual UNIVERSITY UNIVERSITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBDEPARTMENT> SUBDEPARTMENTs { get; set; }
    }
}
