//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.Comments = new HashSet<Comment>();
            this.EventPhotos = new HashSet<EventPhoto>();
            this.EventPhotos1 = new HashSet<EventPhoto>();
            this.EventPhotos2 = new HashSet<EventPhoto>();
            this.EventPhotos3 = new HashSet<EventPhoto>();
            this.EventPhotos4 = new HashSet<EventPhoto>();
            this.EventPhotos5 = new HashSet<EventPhoto>();
            this.EventPhotos6 = new HashSet<EventPhoto>();
            this.EventRegistrations = new HashSet<EventRegistration>();
            this.EventWinners = new HashSet<EventWinner>();
            this.EventWinners1 = new HashSet<EventWinner>();
            this.EventWinners2 = new HashSet<EventWinner>();
            this.EventWinners3 = new HashSet<EventWinner>();
            this.EventWinners4 = new HashSet<EventWinner>();
            this.EventWinners5 = new HashSet<EventWinner>();
            this.EventWinners6 = new HashSet<EventWinner>();
            this.EventVideos = new HashSet<EventVideo>();
        }
    
        public Nullable<int> ClubID { get; set; }
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventStartDateAndTime { get; set; }
        public System.DateTime EventEndDateAndTime { get; set; }
        public Nullable<System.DateTime> EventCreatedDate { get; set; }
        public string EventPoster { get; set; }
        public string EventBrochure { get; set; }
        public Nullable<int> NoOfLikes { get; set; }
        public Nullable<int> NoOfDislikes { get; set; }
        public string QRContentText { get; set; }
        public string QRImage { get; set; }
        public int EventOrganizerID { get; set; }
        public int ApprovalStatusID { get; set; }
        public string RegistrationURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EventBannerPath { get; set; }
        public string EventStatus { get; set; }
        public string BudgetDocumentPath { get; set; }
        public string ManualSheetPath { get; set; }
        public string EventBudget { get; set; }
        public string EventFormPath { get; set; }
        public string ApprovedAmount { get; set; }
        public string RejectionReason { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> LastAlertSentDate { get; set; }
    
        public virtual ApprovalStatusTable ApprovalStatusTable { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable1 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable2 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable3 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable4 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable5 { get; set; }
        public virtual ApprovalStatusTable ApprovalStatusTable6 { get; set; }
        public virtual CLUB CLUB { get; set; }
        public virtual CLUB CLUB1 { get; set; }
        public virtual CLUB CLUB2 { get; set; }
        public virtual CLUB CLUB3 { get; set; }
        public virtual CLUB CLUB4 { get; set; }
        public virtual CLUB CLUB5 { get; set; }
        public virtual CLUB CLUB6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventPhoto> EventPhotos6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRegistration> EventRegistrations { get; set; }
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        public virtual Login Login3 { get; set; }
        public virtual Login Login4 { get; set; }
        public virtual Login Login5 { get; set; }
        public virtual Login Login6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWinner> EventWinners6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventVideo> EventVideos { get; set; }
    }
}
