//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventVideo
    {
        public int Id { get; set; }
        public int EventID { get; set; }
        public string VideoPath { get; set; }
        public System.DateTime UploadedDate { get; set; }
    
        public virtual EVENT EVENT { get; set; }
    }
}
