//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventWinner
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string WinnerName { get; set; }
        public string Prize { get; set; }
        public string Description { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual EVENT EVENT1 { get; set; }
        public virtual EVENT EVENT2 { get; set; }
        public virtual EVENT EVENT3 { get; set; }
        public virtual EVENT EVENT4 { get; set; }
        public virtual EVENT EVENT5 { get; set; }
        public virtual EVENT EVENT6 { get; set; }
    }
}
