//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int RegistrationID { get; set; }
        public int EventID { get; set; }
        public string TypeOfParticipation { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> NumberOfMembers { get; set; }
        public string MemberNames { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string EnrollmentId { get; set; }
        public string UniversityName { get; set; }
        public string Branch { get; set; }
        public string YearOfStudy { get; set; }
        public Nullable<System.DateTime> RegisteredAt { get; set; }
    
        public virtual EVENT EVENT { get; set; }
    }
}
