//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Login Login1 { get; set; }
        public virtual Login Login2 { get; set; }
        public virtual Login Login3 { get; set; }
        public virtual Login Login4 { get; set; }
        public virtual Login Login5 { get; set; }
        public virtual Login Login6 { get; set; }
    }
}
